# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Name')),
                ('slug', models.SlugField(help_text=b'Used for URLS, auto-generated from name if blank', verbose_name=b'Slug', blank=True)),
                ('meta', models.TextField(help_text=b'Meta Description for this category', null=True, verbose_name=b'Meta Description', blank=True)),
                ('description', models.TextField(help_text=b'Optional', verbose_name=b'Description', blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Active')),
                ('parent', models.ForeignKey(related_name='child', blank=True, to='products.Category', null=True)),
                ('related_categories', models.ManyToManyField(related_name='related_categories_rel_+', verbose_name=b'Related Cateogories', to='products.Category', blank=True)),
                ('site', models.ManyToManyField(to='sites.Site', verbose_name=b'Site')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('caption', models.CharField(max_length=100, null=True, verbose_name=b'Optional caption', blank=True)),
                ('sort', models.IntegerField(default=0, verbose_name=b'Sort Order')),
                ('category', models.ForeignKey(related_name='images', blank=True, to='products.Category', null=True)),
            ],
            options={
                'verbose_name': 'Category Image',
                'verbose_name_plural': 'Category Images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(help_text=b'This is what the product will be called in the default site language.  To add non-default translations, use the Product Translation section below.', max_length=255, verbose_name=b'Full Name')),
                ('slug', models.SlugField(help_text=b'Used for urls, autogenerated from blank', verbose_name=b'Slug Name', blank=True)),
                ('short_description', models.TextField(default=b'', help_text=b'This should be 1 or 2 line description of the product.', max_length=200, verbose_name=b'Short Description of product', blank=True)),
                ('meta', models.TextField(help_text=b'Meta description for this product', max_length=200, null=True, verbose_name=b'Meta description', blank=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name=b'Date added', null=True)),
                ('updated_at', models.DateField(auto_now=True, verbose_name=b'Date modified', null=True)),
                ('active', models.IntegerField(default=True, help_text=b'This will determine whether a product should be active for display or not', verbose_name=b'Active')),
                ('featured', models.BooleanField(default=False, help_text=b'Featured Items will show on the front page', verbose_name=b'Featured')),
                ('weight', models.DecimalField(null=True, verbose_name=b'Weight', max_digits=6, decimal_places=2, blank=True)),
                ('weight_units', models.CharField(max_length=3, null=True, verbose_name=b'Weight Units', blank=True)),
                ('width', models.DecimalField(null=True, verbose_name=b'Width', max_digits=6, decimal_places=2, blank=True)),
                ('height', models.CharField(max_length=3, null=True, verbose_name=b'Height', blank=True)),
                ('height_units', models.DecimalField(null=True, verbose_name=b'Height Units', max_digits=6, decimal_places=2, blank=True)),
                ('price', models.DecimalField(verbose_name=b'Price', max_digits=6, decimal_places=2)),
                ('category', models.ManyToManyField(to='products.Category', verbose_name=b'Category', blank=True)),
                ('site', models.ManyToManyField(to='sites.Site', verbose_name=b'Site')),
            ],
            options={
                'verbose_name': 'Product Page',
                'verbose_name_plural': 'Products Page',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('image', models.ImageField(upload_to=b'products/images')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(to='products.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='categoryimage',
            unique_together=set([('category', 'sort')]),
        ),
    ]
